project:
  type: website
  output-dir: _site
  resources:
    - "commonmeta_v0.15.json"
  preview:
    port: 4400
execute:
  freeze: true
website:
  title: "Commonmeta Documentation"
  favicon: favicon.ico
  site-url: https://docs.commonmeta.org
  repo-url: https://github.com/commonmeta/commonmeta
  repo-subdir: docs
  repo-actions: [edit, issue]
  navbar:
    background: light
    logo: "/images/icon.png"
    logo-alt: "Commonmeta"
    right:
      - icon: github
        href: https://github.com/commonmeta/commonmeta
  sidebar:
    contents:
      - index.qmd
      - challenges.qmd
      - implementations.qmd
      - use-cases.qmd
      - schema.qmd
  page-footer:
    left: "Copyright &copy;2023-2025 Commonmeta."
    right:
      - icon: envelope
        href: mailto:info@front-matter.io
      - icon: mastodon 
        href: https://indieweb.social/@commonmeta

format:
  html:
    theme:
      light: [flatly, theme.scss]
      dark: [darkly, theme.scss]
    page-layout: article
    toc: true
    toc-location: right
